raw_data_path: "/opt/airflow/data/raw"
log_file: "/opt/airflow/logs/etl.log"

datasets:
  olist_customers_dataset: customers
  olist_geolocation_dataset: geolocation
  olist_orders_dataset: orders
  olist_order_items_dataset: order_items
  olist_order_payments_dataset: order_payments
  olist_order_reviews_dataset: order_reviews
  olist_products_dataset: products
  olist_sellers_dataset: sellers
  product_category_name_translation: category_translation
